[en]
    languageName = "Yaran magazine"
    title        = "Deconstructing classics, reshaping values"
    weight       = 1

    [en.params.sidebar]
        subtitle = "Tell yesterday’s story in today’s language"

[zh]
    languageName = "雅然丛刊"
    title        = "解构经典，重塑价值"
    weight       = 2

    [zh.params.sidebar]
        subtitle = "用今天的语言讲好昨天的故事"

[zh-hant-tw]
    languageName = "雅然叢刊"
    title        = "解構經典，重塑價值"
    weight       = 3

    [zh-hant-tw.params.sidebar]
        subtitle = "用今天的語言講好昨天的故事"

[ja]
    languageName = "雅然叢刊"
    title        = "解構經典，重塑價值"
    weight       = 4

    [ja.params.sidebar]
        subtitle = "昨日の物語を今日の言葉で上手に語る"
